// Xenoscience / machine-automatic science (Layer 8).
//
// Hidden dynamics are given to the world, never to the scientist. The scientist receives only
// observation channels (no "gravity", "gene", "inheritance", "quantum"). Variables are generated by
// generic operators and kept when they change prediction/discrimination. Comparison with inherited
// human categories is a separate report and never the success criterion.
import type { Preset } from '../core/experiment.ts';
import type { WorldSpec, RuleSpec } from '../core/types.ts';
import type { Trace } from '../core/trace.ts';
import { observationSeries } from '../analysis/samples.ts';
import { grammarBoundedDiscovery, compareToInherited, lsq } from '../analysis/grammar-bounded.ts';

const n = (p: Record<string, unknown>, k: string, d: number) => (typeof p[k] === 'number' ? (p[k] as number) : d);
const b = (p: Record<string, unknown>, k: string, d: boolean) => (typeof p[k] === 'boolean' ? (p[k] as boolean) : d);

// ---------------------------------------------------------------- hidden attraction ("gravity" never provided)

export const hiddenAttraction: Preset = {
  id: 'science.hidden-attraction', title: 'Variable construction: hidden attraction (supplied grammar)', area: 'variable-construction', layer: 8,
  summary: 'Two bodies separate while decelerating under a hidden inverse-square attraction. The observer receives two position channels and nothing else. Does machine variable construction produce a predictive variable, and does it isolate the same difference as the inherited category "gravity"?',
  defaults: { seed: 1, horizon: 160, G: 20, law: 2, noise: 0 },
  build: (p): WorldSpec => {
    const G = n(p, 'G', 20), law = n(p, 'law', 2), dt = 0.1;
    return {
      id: 'science.hidden-attraction', seed: n(p, 'seed', 1), horizon: n(p, 'horizon', 160),
      config: [{ key: 'provided-vocabulary', value: [], status: 'specified' }, { key: 'hidden-law-exponent', value: law, status: 'unknown' }],
      state: { 'q/0': 0, 'q/1': 10, 'hidden/v0': -0.9, 'hidden/v1': 0.9 },
      clocks: [{ id: 'dyn', period: 1 }],
      rules: [{ id: 'hidden.dynamics', clock: 'dyn', when: () => true, then: (c, e) => {
        const d = c.get('q/1') - c.get('q/0'); const a = G / Math.pow(Math.abs(d), law) * Math.sign(d);
        const v0 = c.get('hidden/v0') + a * dt, v1 = c.get('hidden/v1') - a * dt;
        e.set('hidden/v0', v0); e.set('hidden/v1', v1); e.add('q/0', v0 * dt); e.add('q/1', v1 * dt);
      } }],
      apparatus: [{ id: 'P', label: 'position channels only', channels: [
        { id: 'x0', clock: 'dyn', reads: ['q/0'], noise: n(p, 'noise', 0) }, { id: 'x1', clock: 'dyn', reads: ['q/1'], noise: n(p, 'noise', 0) },
      ] }],
    };
  },
};

export function discoverFromTrace(tr: Trace, G = 20, law = 2) {
  const S = observationSeries(tr, 'P', ['x0', 'x1']);
  const res = grammarBoundedDiscovery(S, { minGain: 0.05, maxAccept: 5 });
  // Inherited human category (separate report): acceleration ∝ 1/r² on body 0.
  const sep = S.x1.map((v, i) => v - S.x0[i]);
  const inherited = { 'gravity (inverse-square acceleration)': sep.map((d) => G / Math.pow(Math.abs(d), law)) };
  const claims = res.accepted.map((g) => /inv_sq\(sub/.test(g.expr)
    ? `${g.id}: the system selected an inverse-square relational variable (${g.expr}) from the supplied construction grammar under this configuration`
    : `${g.id}: selected ${g.expr} from the supplied construction grammar`);
  return { ...res, accepted: res.accepted.map(({ values, ...g }) => g), inheritedComparison: compareToInherited(res.accepted, inherited), claims,
    claimStrength: 'grammar-bounded selection (operators, variable type, apparatus and temporal scale were all supplied)' };
}

// ---------------------------------------------------------------- delayed / windowed hidden law (grammar morphogenesis testbed)

export const delayedLaw: Preset = {
  id: 'science.delayed-law', title: 'Variable construction: hidden law outside the supplied grammar', area: 'variable-construction', layer: 8,
  summary: 'A single observed channel follows a hidden law with a delayed feedback term; halfway through, the law switches to a thresholded windowed term. Neither is expressible with the initial variables or with the supplied depth-2 grammar (no delays, windows or thresholds). Kicks are applied as interventions.',
  questions: ['Which model class recovers prediction after the hidden-law switch?', 'Does the construction grammar itself change, and for which operational criterion?'],
  defaults: { seed: 5, horizon: 320, lag: 6, window: 8, switchAt: 160, noise: 0.15 },
  build: (p): WorldSpec => {
    const L = n(p, 'lag', 6), W = n(p, 'window', 8), sw = n(p, 'switchAt', 160), nz = n(p, 'noise', 0.15);
    return {
      id: 'science.delayed-law', seed: n(p, 'seed', 5), horizon: n(p, 'horizon', 320),
      config: [{ key: 'provided-vocabulary', value: [], status: 'specified' }, { key: 'hidden-law', status: 'unknown' }],
      state: { x: 1 },
      clocks: [{ id: 'dyn', period: 1 }, { id: 'obs', period: 1, phase: 0.5 }],
      rules: [{ id: 'hidden.law', clock: 'dyn', when: () => true, then: (c, e) => {
        const x = c.get('x');
        let next: number;
        if (c.t < sw) next = 0.55 * x - 0.4 * c.hist('x', L) + nz * (c.rng() * 2 - 1); // |0.55|+|0.4| < 1: stable
        else { let m = 0; for (let k = 0; k < W; k++) m += c.hist('x', k); m /= W; next = 0.8 * x - 0.3 * Math.sign(m) + nz * (c.rng() * 2 - 1); }
        e.set('x', next);
      } }],
      interventions: [60, 120, 200, 260].map((t, i) => ({ id: `kick${i}`, t: t + 0.25, kind: 'add' as const, address: 'x', value: 1.5 })),
      apparatus: [{ id: 'O', label: 'single channel', channels: [{ id: 'x', clock: 'obs', reads: ['x'] }] }],
    };
  },
};

// ---------------------------------------------------------------- persistence across replacement ("heredity" never provided)

export const replacementPersistence: Preset = {
  id: 'science.replacement-persistence', title: 'Variable construction: persistence across replacement', area: 'variable-construction', layer: 8,
  summary: 'Eight slots hold individuals with a hidden value; the observer sees only noisy phenotypes and a birth counter per slot. When a slot is refilled, is the newcomer closer to some existing member than chance? No gene, parent or lineage is provided.',
  defaults: { seed: 21, horizon: 300, slots: 8, inheritance: true, mutation: 0.08, envNoise: 0.05 },
  build: (p): WorldSpec => {
    const K = n(p, 'slots', 8), inh = b(p, 'inheritance', true), mut = n(p, 'mutation', 0.08), en = n(p, 'envNoise', 0.05);
    const state: Record<string, number> = { 'env/optimum': 0 };
    for (let i = 0; i < K; i++) { state[`hidden/g/${i}`] = (i - K / 2) / K * 2; state[`ph/${i}`] = state[`hidden/g/${i}`]; state[`birth/${i}`] = 0; }
    const rules: RuleSpec[] = [
      { id: 'env.drift', clock: 'gen', when: () => true, then: (c, e) => e.set('env/optimum', 0.6 * Math.sin(c.t / 60)) },
      { id: 'phenotype', clock: 'gen', when: () => true, then: (c, e) => { for (let i = 0; i < K; i++) e.set(`ph/${i}`, c.get(`hidden/g/${i}`) + en * (c.rng() * 2 - 1)); } },
      { id: 'turnover', clock: 'gen', when: () => 0.5, then: (c, e) => {
        const opt = c.get('env/optimum');
        let worst = 0, wv = -1; for (let i = 0; i < K; i++) { const d = Math.abs(c.get(`hidden/g/${i}`) - opt) + 0.3 * c.rng(); if (d > wv) { wv = d; worst = i; } }
        let par = Math.floor(c.rng() * K); if (par === worst) par = (par + 1) % K;
        const g = inh ? c.get(`hidden/g/${par}`) + mut * (c.rng() * 2 - 1) : 2 * (c.rng() * 2 - 1);
        e.set(`hidden/g/${worst}`, g); e.add(`birth/${worst}`, 1);
      } },
    ];
    const channels = [];
    for (let i = 0; i < K; i++) channels.push({ id: `p${i}`, clock: 'gen', reads: [`ph/${i}`], resolution: 0.001 }, { id: `b${i}`, clock: 'gen', reads: [`birth/${i}`] });
    return {
      id: 'science.replacement-persistence', seed: n(p, 'seed', 21), horizon: n(p, 'horizon', 300),
      config: [{ key: 'provided-vocabulary', value: [], status: 'specified' }], state, rules,
      clocks: [{ id: 'gen', period: 1, label: 'biological turnover' }],
      apparatus: [{ id: 'O', label: 'phenotype + birth counters', channels }],
    };
  },
};

/**
 * Generic relational operator: at each observed replacement, distance from the newcomer to the nearest
 * *other* current member, versus the same statistic for a random draw from the phenotype pool.
 * A ratio ≪ 1 makes "persistence across replacement" a non-redundant distinction.
 */
export function persistenceAcrossReplacement(tr: Trace, K = 8) {
  const O = tr.observations.O;
  const T = O.p0.length;
  const P = (i: number, t: number) => O[`p${i}`][t][1] as number;
  const B = (i: number, t: number) => O[`b${i}`][t][1] as number;
  const near: number[] = [], chance: number[] = [];
  const pool: number[] = []; for (let t = 0; t < T; t++) for (let i = 0; i < K; i++) pool.push(P(i, t));
  let r = 12345; const rnd = () => ((r = (r * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff);
  for (let t = 2; t < T; t++) for (let i = 0; i < K; i++) {
    if (B(i, t) === B(i, t - 1)) continue;
    const newcomer = P(i, t);
    const others = Array.from({ length: K }, (_, j) => j).filter((j) => j !== i).map((j) => P(j, t - 1));
    near.push(Math.min(...others.map((o) => Math.abs(o - newcomer))));
    const fake = pool[Math.floor(rnd() * pool.length)];
    chance.push(Math.min(...others.map((o) => Math.abs(o - fake))));
  }
  const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / Math.max(1, xs.length);
  const ratio = mean(near) / (mean(chance) || 1);
  return { replacements: near.length, meanNearest: mean(near), meanChance: mean(chance), ratio, nonRedundant: near.length >= 10 && ratio < 0.6,
    generatedDistinction: 'rel:nearest-other-at-replacement / rel:nearest-other-of-random-draw' };
}

// ---------------------------------------------------------------- inherited category retention ("discreteness")

export const stepResponse: Preset = {
  id: 'science.step-response', title: 'Inherited category test: discreteness', area: 'variable-construction', layer: 8,
  summary: 'A graded input sweeps a hidden system. In one configuration the response comes in plateaus; in the other it is graded. Is the inherited distinction "discrete levels" retained, i.e. does it change prediction beyond a graded model?',
  defaults: { seed: 2, horizon: 200, discrete: true, levels: 4, noise: 0.02 },
  build: (p): WorldSpec => {
    const disc = b(p, 'discrete', true), L = n(p, 'levels', 4), nz = n(p, 'noise', 0.02);
    return {
      id: 'science.step-response', seed: n(p, 'seed', 2), horizon: n(p, 'horizon', 200),
      state: { u: 0, y: 0 },
      // Input, response and measurement run on phase-shifted clocks so the response follows its input.
      clocks: [{ id: 's', period: 1, label: 'input' }, { id: 'r', period: 1, phase: 0.25, label: 'response' }, { id: 'm', period: 1, phase: 0.5, label: 'measurement' }],
      rules: [
        { id: 'sweep', clock: 's', when: () => true, then: (c, e) => e.set('u', (c.t % 100) / 100 * L) },
        { id: 'hidden.response', clock: 'r', when: () => true, then: (c, e) => { const u = c.get('u'); e.set('y', (disc ? Math.floor(u) : u) + nz * (c.rng() * 2 - 1)); } },
      ],
      apparatus: [{ id: 'R', channels: [{ id: 'u', clock: 'm', reads: ['u'] }, { id: 'y', clock: 'm', reads: ['y'] }] }],
    };
  },
};

export function categoryRetention(tr: Trace, levels = 4) {
  const S = observationSeries(tr, 'R', ['u', 'y']);
  const u = S.u.slice(2), y = S.y.slice(2);
  const nrm = y.length;
  const lin = lsq(u.map((x) => [1, x]), y) / nrm;
  const ind = (x: number) => Array.from({ length: levels }, (_, k) => (Math.floor(x) === k ? 1 : 0));
  const step = lsq(u.map((x) => [...ind(x)]), y) / nrm;
  const gain = (lin - step) / (lin || 1);
  return { gradedError: lin, discreteError: step, relativeGain: gain, retained: gain > 0.5,
    verdict: gain > 0.5 ? 'inherited distinction non-redundant here' : 'inherited distinction redundant here (graded model suffices)' };
}

export const SCIENCE_PRESETS = [hiddenAttraction, replacementPersistence, stepResponse, delayedLaw];
