// Runs the External Framework Comparison Benchmarks and writes machine-readable results plus a generated report.
// Usage: node comparison/run.ts   → results/external-comparison/*.json, docs/external-results.md
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { runExternalComparison, forbiddenFieldsIn } from './bench.ts';
import { CASCADED_TANKS, validateProvenance } from './empirical/provenance.ts';

const root = (p: string) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const t0 = Date.now();
const R = runExternalComparison();
const bad = forbiddenFieldsIn(R);
if (bad.length) { console.error('forbidden fields present:', bad); process.exit(1); }

mkdirSync(root('results/external-comparison'), { recursive: true });
const stripTiming = (x: unknown): unknown => JSON.parse(JSON.stringify(x, (k, v) => (k === 'computeMs' ? undefined : v)));
for (const w of R.worlds) writeFileSync(root(`results/external-comparison/${w.world}.json`), JSON.stringify(stripTiming(w), null, 2) + '\n');
writeFileSync(root('results/external-comparison/ablations.json'), JSON.stringify(R.ablations, null, 2) + '\n');
writeFileSync(root('results/external-comparison/negative-results.json'), JSON.stringify(R.negativeResults, null, 2) + '\n');
writeFileSync(root('results/external-comparison/definitions.json'), JSON.stringify(R.definitions, null, 2) + '\n');
writeFileSync(root('results/external-comparison/empirical-candidate.json'), JSON.stringify({ ...CASCADED_TANKS, missingRequiredFields: validateProvenance(CASCADED_TANKS) }, null, 2) + '\n');
writeFileSync(root('results/external-comparison/index.json'), JSON.stringify({ suite: 'External Framework Comparison Benchmarks', branch: 'research/external-comparison', baseRelease: 'v0.3.0 (frozen)', claimStatus: R.claimStatus, node: process.version, worlds: R.worlds.map((w) => ({ world: w.world, records: w.records.length, fairnessChecks: w.fairness.length, notApplicable: w.notApplicable.map((n) => n.framework) })), ablations: R.ablations.length, negativeResults: R.negativeResults.length, note: 'computeMs fields are omitted from the JSON files because wall time is machine-dependent; they appear in docs/external-results.md' }, null, 2) + '\n');

// ------------------------------------------------------------------ generated report
const esc = (s: unknown) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const fmt = (v: unknown) => (v === undefined ? '—' : v === null ? 'n/a' : Array.isArray(v) ? (v.length ? v.join(', ') : '∅') : typeof v === 'object' ? JSON.stringify(v) : String(v));
const o: string[] = ['# External comparison — results (generated)', '',
  `Generated by \`node comparison/run.ts\` on branch \`research/external-comparison\` · Node ${process.version}. Base release v0.3.0 is unchanged.`, '',
  '**All results are synthetic-world results.** No framework is ranked and no global score is computed. Each table reports measurements per configuration; statements use the form "under configuration C and implementation B, distinction D was (not) retained". See [external-comparison.md](external-comparison.md) for the protocol, [baseline-definitions.md](baseline-definitions.md) for each baseline and [comparison-limitations.md](comparison-limitations.md) for what these results do not show.', ''];
for (const w of R.worlds) {
  o.push(`## ${w.world}`, '', `**Question.** ${w.question}`, '', `**Design.** ${w.design}`, '');
  const keys = [...new Set(w.records.flatMap((r) => Object.keys(r.measurements)))].filter((k) => !/seed1|perSeed|_actual|_predicted|judgement/.test(k)).slice(0, 12);
  o.push(`| role | framework | configuration | ${keys.map(esc).join(' | ')} |`, `|---|---|---|${keys.map(() => '---').join('|')}|`);
  for (const r of w.records) o.push(`| ${r.role} | ${r.framework} | ${esc(r.configuration)} | ${keys.map((k) => esc(fmt(r.measurements[k]))).join(' | ')} |`);
  o.push('', '**Per-distinction table**', '', '| distinction | retained by | not retained by | n/a |', '|---|---|---|---|');
  for (const d of w.distinctionTable) o.push(`| ${esc(d.distinction)} | ${esc(d.retainedBy.join('; '))} | ${esc(d.notRetainedBy.join('; '))} | ${esc(d.notApplicable.join('; '))} |`);
  o.push('', '**Fairness checks**', '');
  for (const f of w.fairness) o.push(`- *${esc(f.distinction)}*: ${esc(f.firstConfiguration)} → ${esc(f.alternativeConfiguration)} — ${f.alternativeTested ? `retained under alternative: ${f.retainedUnderAlternative}` : 'not run'}. ${esc(f.note)}`);
  o.push('', `**References.** ${esc(JSON.stringify(w.references))}`, '', `**Not applicable.** ${w.notApplicable.map((n) => `${n.framework} — ${n.reason}`).join('; ')}`, '');
  o.push('**Compute (wall time, this machine, all seeds):** ' + w.records.map((r) => `${r.configuration.split(' (')[0]} ${r.cost.computeMs} ms`).join(' · '), '');
}
o.push('## Ablations of the Ziran / Xeno adapter', '', '| mechanism | world | changed a measurement | detail |', '|---|---|---|---|');
for (const a of R.ablations) o.push(`| ${esc(a.mechanism)} | ${a.world} | ${a.changed ? 'yes' : '**no**'} | ${esc(a.detail)} |`);
o.push('', '## Negative and null results (derived from the records)', '', ...R.negativeResults.map((n) => `- ${esc(n)}`), '');
writeFileSync(root('docs/external-results.md'), o.join('\n'));
console.log(`External Framework Comparison: ${R.worlds.length} worlds, ${R.worlds.reduce((s, w) => s + w.records.length, 0)} configurations, ${R.ablations.length} ablations (${R.ablations.filter((a) => !a.changed).length} without measured difference), ${R.negativeResults.length} negative/null statements, ${Date.now() - t0} ms`);
